from pybuilder.core import use_plugin, init, Author

use_plugin("python.core")
use_plugin("python.install_dependencies")
use_plugin("python.flake8")
use_plugin("python.distutils")
use_plugin('pypi:pybuilder_header_plugin')
use_plugin('pypi:pybuilder_release_plugin')


name = "pybuilder_jedi_plugin"
default_task = ["analyze", "check_source_file_headers", "publish"]
url = "https://github.com/mriehl/pybuilder_jedi_plugin"
description = "Lints your sources with the jedi"
authors = [Author('Maximilien Riehl', 'max@riehl.io')]
license = 'Apache License, Version 2.0'
version = '0.0.1'


@init
def set_properties(project):
    project.depends_on('committer')
    project.set_property('verbose', True)
    project.set_property('flake8_break_build', True)
    project.set_property('pybuilder_header_plugin_break_build', True)
    project.set_property('pybuilder_header_plugin_expected_header', """#
# autogenerated by pybuilder header plugin
# Copyright 2014 Maximilien Riehl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.""")

    project.set_property('distutils_classifiers', [
        'Development Status :: 1 - Planning',
        'Environment :: Console',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: Apache Software License',
        'Programming Language :: Python',
        'Programming Language :: Python :: 2',
        'Programming Language :: Python :: 2.7',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.0',
        'Programming Language :: Python :: 3.1',
        'Programming Language :: Python :: 3.2',
        'Programming Language :: Python :: 3.3',
        'Topic :: Utilities']
    )
